// <auto-generated />
using System;
using IES.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IES.Migrations
{
    [DbContext(typeof(IESContext))]
    [Migration("20201225151116_Course-Discipline")]
    partial class CourseDiscipline
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Model.Registrations.Course", b =>
                {
                    b.Property<long?>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Model.Registrations.CourseDiscipline", b =>
                {
                    b.Property<long?>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DisciplineId")
                        .HasColumnType("bigint");

                    b.HasKey("CourseId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("CourseDiscipline");
                });

            modelBuilder.Entity("Model.Registrations.Department", b =>
                {
                    b.Property<long?>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Model.Registrations.Discipline", b =>
                {
                    b.Property<long?>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Model.Registrations.Institution", b =>
                {
                    b.Property<long?>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Model.Registrations.Course", b =>
                {
                    b.HasOne("Model.Registrations.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Model.Registrations.CourseDiscipline", b =>
                {
                    b.HasOne("Model.Registrations.Course", "Course")
                        .WithMany("CoursesDisciplines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Registrations.Discipline", "Discipline")
                        .WithMany("CoursesDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Model.Registrations.Department", b =>
                {
                    b.HasOne("Model.Registrations.Institution", "Institution")
                        .WithMany("Departments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Model.Registrations.Course", b =>
                {
                    b.Navigation("CoursesDisciplines");
                });

            modelBuilder.Entity("Model.Registrations.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Model.Registrations.Discipline", b =>
                {
                    b.Navigation("CoursesDisciplines");
                });

            modelBuilder.Entity("Model.Registrations.Institution", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
